networks:
  sparql:
    driver: bridge
services:
  grasp:
    build: /Users/mielvandersande/Meemoo/Development/grasp/grasp
    environment:
      - RESOURCES_DIR=/grasp/resources
      - SERVICES_FILE=/grasp/services.json
      - MAX_BATCH_SIZE=100
      - LOG_LEVEL=info
      - CACHE_TTL=300000
      - CACHE_SIZE=200
    ports:
      - "4000:4000"
    volumes:
      - "$PWD/resources:/grasp/resources"
      - "$SERVICES_FILE:/grasp/services.json"
    networks:
      - sparql
