PREFIX : <https://github.com/dbcls/grasp/ns/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX haOrg: <https://data.hetarchief.be/ns/organization/>
PREFIX schema: <https://schema.org/>

CONSTRUCT {
  ?iri :iri  ?iri;
  :contact_type ?contact_type;
  :email ?email;
  :telephone ?telephone                            
}
FROM <https://data.hetarchief.be/graph/organization>
WHERE
{
  { ?iri a schema:ContactPoint }
  OPTIONAL { ?iri schema:contactType ?contact_type }
  OPTIONAL { ?iri schema:email ?email }
  OPTIONAL { ?iri schema:telephone ?telephone }
  
  {{#if iri}}
  VALUES ?iri { {{join " " (as-iriref iri)}} }
  {{/if}}
}