PREFIX : <https://github.com/dbcls/grasp/ns/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?iri :iri ?iri; :address ?a .
}
FROM <https://data.hetarchief.be/graph/organization>
WHERE
{
  { ?iri a org:Site }
  OPTIONAL { ?iri org:siteAddress ?a }

  {{#if iri}}
  VALUES ?iri { {{join (as-iriref iri) " "}} }
  {{/if}}
}